### PR TITLE
Fix to Issue#66 (Simple Text Report).htmlLogScraper.py script will re…

### PR DESCRIPTION
**Pull request by pgb6**
…turn a .csv file when run on te command line given that the user specifies the path of the html logfile. .csv file will be put into the /logs directory.

### CODE REVIEW

**Comment by tomasg2012** [comment]
I apologize to mention that a csv_report option is already in the tool.  The issue just seems to not be closed.  However, the additional file is useful.

**Comment by jautor** [comment]
@tomasg2012 and @pgb6 please discuss the best approach to merge this functionality with the existing work.  We'll want a file output as the end result..

**Comment by pgb6** [comment]
The script I provided was made using Python's argparse module. I propose that we add the argument from my script into the Interop Validator parser  and add in the 'htmlLogScraper' function. It is important to note that this function must be called after the InteropHtmlLog is generated since it uses these logs as input.
1. Do we keep the --csv_report argument?
2. We should also update the README after this integration to make the user aware of this new argument.

**Comment by tomasg2012** [comment]
Just realized I can't push my modifications to this pull request specifically, I will ask if this is satisfactory for a pull request and README and changes can be updated by next week.  No major changes are really needed here, as we decided the tool itself is useful for logs generated after a run, unlike the current --csv_report.  It also generates a file, which csv_report does not.

**Comment by mraineri** [comment]
Approved 1/16

**Pull request merged**
