### PR TITLE
Added new logic for UseCaseType

### PR DESCRIPTION
**Pull request by tomasg2012**
Added UseCaseType logic for "Normal" and "AbsentResource".

### CODE REVIEW

**Comment by mraineri** [comment]
Hitting an issue with the following profile. I think it's uncovering an issue where it's mapping in a use case that shouldn't be pulled in. When testing against public-rackmount1, DIMM4 has "Absent" for its state, and it's testing the new UseCaseType term properly there. However, it's also testing against the "NV-DIMM" use case, which is not expected. It might be because "MemoryType" is not in the response payload, and hitting "MemoryType does not equal DRAM"; if the use case key property doesn't exist in the response, there shouldn't be any matching criteria for the use case.

```
{
    "SchemaDefinition": "RedfishInteroperabilityProfile.v1_7_0",
    "ProfileName": "UseCaseTypeTest",
    "ProfileVersion": "1.0.0",
    "Resources": {
        "Memory": {
            "UseCases": [
                {
                    "UseCaseTitle": "DIMM URIs",
                    "URIs": [
                        "/redfish/v1/Systems/{ComputerSystemsId}/Memory/{MemoryId}"
                    ]
                },
                {
                    "UseCaseTitle": "Missing DIMM",
                    "UseCaseType": "AbsentResource",
                    "PropertyRequirements": {
                        "Location": {},
                        "MemoryLocation": {}
                    }
                },
                {
                    "UseCaseTitle": "DRAM",
                    "UseCaseKeyProperty": "MemoryType",
                    "UseCaseComparison": "Equal",
                    "UseCaseKeyValues": [
                        "DRAM"
                    ],
                    "UseCaseType": "Normal",
                    "PropertyRequirements": {
                        "CapacityMiB": {},
                        "Location": {},
                        "MemoryLocation": {}
                    }
                },
                {
                    "UseCaseTitle": "NV-DIMM",
                    "UseCaseKeyProperty": "MemoryType",
                    "UseCaseComparison": "NotEqual",
                    "UseCaseKeyValues": [
                        "DRAM"
                    ],
                    "MinVersion": "1.13.0",
                    "PropertyRequirements": {
                        "CapacityMiB": {},
                        "ConfigurationLocked": {},
                        "EnvironmentMetrics": {},
                        "Location": {},
                        "Manufacturer": {},
                        "MemoryDeviceType": {},
                        "MemoryMediaType": {},
                        "Metrics": {},
                        "ModuleProductID": {},
                        "NonVolatileSizeMiB": {},
                        "OperatingSpeed": {},
                        "PartNumber": {},
                        "SerialNumber": {},
                        "Status": {},
                        "VolatileSizeMiB": {}
                    }
                }
            ]
        }
    }
}
```

**Comment by tomasg2012** [comment]
Latest changes should be accurate

```
*** /redfish/v1/Systems/437XR1138R2/Memory/DIMM4, Memory
         Type (#Memory.v1_20_0.Memory), GET SUCCESS (time: 0)
### Validating an InteropResource
Validating using UseCase DIMM_URIs
### Validating an InteropResource
Validating using UseCase Missing_DIMM
### Validating an InteropResource
### Validating PropertyRequirements for Location
### Validating PropertyRequirements for MemoryLocation
UseCase DRAM does not apply
UseCase NV-DIMM does not apply
```

**Comment by mraineri** [comment]
Updates look good! Not finding any other issues.

**Comment by mraineri** [comment]
Approved

**Pull request merged**
