### PR TITLE
Adds Replacement-based profile properties

### LINKED ISSUE #170: Add support for ReplacedByProperty / ReplacesProperty functionality
Can the Interop-Validator be updated to handle the newly introduced `ReplacedByProperty` / `ReplacesProperty` functions? I'm in the process of removing our clunky conditionals and replacing with `ReplacedByProperty` / `ReplacesProperty`, however the Interop-Validator doesn't support this yet and as a result our (previously) passing tests are now failing.

### PR DESCRIPTION
**Pull request by tomasg2012**
Fixes #170 

Adds ReplacedByProperty and ReplacesProperty from latest profile language.

Normalized terminology, added notes and added REDFISH_ABSENT constant

[replaced-logs.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/11366585/replaced-logs.zip)

### CODE REVIEW

**Comment by mraineri** [comment]
When unit testing, I noticed that when I remove both properties (the one replaced and the one doing the replacing) from the payload, the test correctly flags a failure in the summary and in the property table, but the error message box shows "No errors".

image

And this is the profile I'm using for testing:

```
{
    "SchemaDefinition": "RedfishInteroperabilityProfile.v1_6_0",
    "ProfileName": "Replacement",
    "ProfileVersion": "1.0.0",
    "Resources": {
        "Chassis": {
            "PropertyRequirements": {
                "Thermal": {
                    "ReplacedByProperty": "ThermalSubsystem"
                },
                "ThermalSubsystem": {
                    "ReplacesProperty": "Thermal"
                }
            }
        },
        "ComputerSystem": {
            "PropertyRequirements": {
                "IndicatorLED": {
                    "ReplacedByProperty": "LocationIndicatorActive"
                },
                "LocationIndicatorActive": {
                    "ReplacesProperty": "IndicatorLED"
                }
            }
        }
    }
}
```

**Comment by mraineri** [comment]
Hitting an issue with some of the JSON pointer usage. In this unit test, I'm tying Location/PostalAddress and Thermal together with this profile:

```
{
    "SchemaDefinition": "RedfishInteroperabilityProfile.v1_6_0",
    "ProfileName": "Replacement",
    "ProfileVersion": "1.0.0",
    "Resources": {
        "Chassis": {
            "PropertyRequirements": {
                "Thermal": {
                    "ReplacedByProperty": "/Location/PostalAddress"
                },
                "Location": {
                    "PropertyRequirements": {
                        "PostalAddress": {
                            "ReplacesProperty": "/Thermal"
                        }
                    }
                }
            }
        },
        "ComputerSystem": {
            "PropertyRequirements": {
                "IndicatorLED": {
                    "ReplacedByProperty": "LocationIndicatorActive"
                },
                "LocationIndicatorActive": {
                    "ReplacesProperty": "IndicatorLED"
                }
            }
        }
    }
}
```

After removing "Thermal" from the payload, I would expect this to pass since "Location/PostalAddress" is present in the payload, but it's resulting in an error stating Thermal is expected:

image

**Comment by tomasg2012** [comment]
Oops, I'll double check why this is the case.  The first one needs a message for both not existing, it should report a warning whenever something isn't replaced.  

The second, maybe not applied properly due to being sub-properties of other objects?

**Comment by mraineri** [comment]
> Oops, I'll double check why this is the case. The first one needs a message for both not existing, it should report a warning whenever something isn't replaced, seems it doesn't even give that.

I did see warnings come up when I had the old property present, but the new one is missing. That part looked good; it's just the other case when both are missing (thus creating an error)

> The second, maybe not applied properly due to being sub-properties of other objects?

Yeah, I suspect it has to do with something along those lines.

**Comment by mraineri** [comment]
Everything looks good! Merging.

**Pull request merged**
