### PR TITLE
Implement UseCases for top-level resources

### PR DESCRIPTION
**Pull request by tomasg2012**
Adds support for UseCases property in profiles for Resources

[usecases-logs.zip](https://github.com/DMTF/Redfish-Interop-Validator/files/11366587/usecases-logs.zip)

### CODE REVIEW

**Comment by tomasg2012** [comment]
Adding a note here, is this supposed to be only implemented for the top-level of a resource and not inside subproperties/Complex objects?  Additionally, should properties being compared to not use JSON Path and only use top-level properties as well?

**Comment by mraineri** [comment]
Correct, it would just be at the top-level (not down inside nested objects).

The compare property I could see as something that might need JSON path support (I don't think it'll necessarily always be a root-level property).

@jautor, and input on this?

**Comment by jautor** [comment]
I would hope that a use case comparison could be determined by something at the root level...  For resources with a number of tech-specific objects you'd want to simply do a compare for presence of the `Infiniband` vs. `Ethernet` objects...  But as soon as we say never - it will come up.  But I'd be happy to say that's an enhancement if and when it comes up.

**Comment by mraineri** [comment]
Using this profile (against the mockup built into the Redfish-Mockup-Server) I'm getting an exception; it looks it's not correctly handling the first use case that's there to document expected URIs. In the case where there's no "UseCaseKeyProperty", there will need logic to reduce the checking based on other definitions (like the URIs term).

```
ERROR - Something went wrong
Traceback (most recent call last):
  File "/share/Redfish/Redfish-Interop-Validator/validateResource.py", line 160, in validateSingleURI
    propMessages, propCounts = interop.validateInteropResource(resource_obj, profile_resources, jsondata)
  File "/share/Redfish/Redfish-Interop-Validator/common/interop.py", line 624, in validateInteropResource
    entry_key, entry_comparison, entry_values = case['UseCaseKeyProperty'], case['UseCaseComparison'], case['UseCaseKeyValues']
KeyError: 'UseCaseKeyProperty'
ERROR - Could not finish validation check on this payload
```

```
{
    "SchemaDefinition": "RedfishInteroperabilityProfile.v1_6_0",
    "ProfileName": "UseCases",
    "ProfileVersion": "1.0.0",
    "Resources": {
        "Memory": {
            "UseCases": [
                {
                    "UseCaseTitle": "System Memory",
                    "URIs": [
                        "/redfish/v1/Systems/{ComputerSystemsId}/Memory/{MemoryId}"
                    ]
                },
                {
                    "UseCaseTitle": "DIMM",
                    "UseCaseKeyProperty": "MemoryType",
                    "UseCaseComparison": "Equal",
                    "UseCaseKeyValues": [
                        "DRAM"
                    ],
                    "ReadRequirement": "IfImplemented",
                    "MinVersion": "1.7.0",
                    "PropertyRequirements": {
                        "CapacityMiB": {},
                        "Location": {},
                        "Manufacturer": {},
                        "ModuleProductID": {},
                        "OperatingSpeed": {},
                        "PartNumber": {}
                    }
                },
                {
                    "UseCaseTitle": "NV-DIMM",
                    "UseCaseKeyProperty": "MemoryType",
                    "UseCaseComparison": "NotEqual",
                    "UseCaseKeyValues": [
                        "DRAM"
                    ],
                    "ReadRequirement": "IfImplemented",
                    "MinVersion": "1.13.0",
                    "PropertyRequirements": {
                        "CapacityMiB": {},
                        "ConfigurationLocked": {},
                        "EnvironmentMetrics": {},
                        "Location": {},
                        "Manufacturer": {},
                        "MemoryDeviceType": {},
                        "MemoryMediaType": {},
                        "Metrics": {},
                        "ModuleProductID": {},
                        "NonVolatileSizeMiB": {},
                        "OperatingSpeed": {},
                        "PartNumber": {},
                        "SerialNumber": {},
                        "Status": {},
                        "VolatileSizeMiB": {}
                    }
                }
            ]
        }
    }
}
```

**Comment by tomasg2012** [comment]
Ah, okay.  UseCases use URIs.  They don't use ConditionalRequirements, do they?  The Spec doesn't list that at least.

**Comment by tomasg2012** [comment]
On the above example, would the program always use the first case and not the second or third case?  At least in practice, all memory modules would be using that URI path.

Or is it expected that multiple cases can apply at once?  I may be mistaken there.

**Comment by mraineri** [comment]
Right, the first use case would always be triggered since it doesn't contain any specific criteria. Not all memory devices need to use that URI path, but there needs to be at least one instance that matches; it's like the URIs rule at the root of the resource object.

Multiple cases can apply at once.

**Comment by tomasg2012** [comment]
So it should seem that a UseCase can also be considered Mandatory, as in it should be considered a failed if that UseCase does not exist, yes?  That's a logical extension of how ReadRequirement for resources works in the program, I just wasn't applying it in the same manner.

Should there be at least one example of that UseCase?  That will be added.

**Comment by mraineri** [comment]
That would be dependent upon the "ReadRequirement" for the UseCase; by default, it's "Mandatory", which would mean at least one instance of the use case needs to be found. In the example above, "ReadRequirement" is "IfImplemented", making it optional.

**Comment by mraineri** [comment]
Looks like it's almost there; one last minor thing. Testing out the "required" use cases. I'm using this as the profile.

```
{
    "SchemaDefinition": "RedfishInteroperabilityProfile.v1_6_0",
    "ProfileName": "UseCases",
    "ProfileVersion": "1.0.0",
    "Resources": {
        "Memory": {
            "UseCases": [
                {
                    "UseCaseTitle": "System Memory",
                    "URIs": [
                        "/redfish/v1/Systems/{ComputerSystemsId}/Memory/{MemoryId}"
                    ]
                },
                {
                    "UseCaseTitle": "DIMM",
                    "UseCaseKeyProperty": "MemoryType",
                    "UseCaseComparison": "Equal",
                    "UseCaseKeyValues": [
                        "DRAM"
                    ],
                    "ReadRequirement": "IfImplemented",
                    "MinVersion": "1.7.0",
                    "PropertyRequirements": {
                        "CapacityMiB": {},
                        "Location": {},
                        "Manufacturer": {},
                        "ModuleProductID": {},
                        "OperatingSpeed": {},
                        "PartNumber": {}
                    }
                },
                {
                    "UseCaseTitle": "NV-DIMM",
                    "UseCaseKeyProperty": "MemoryType",
                    "UseCaseComparison": "Equal",
                    "UseCaseKeyValues": [
                        "Fred"
                    ],
                    "MinVersion": "1.13.0",
                    "PropertyRequirements": {
                        "CapacityMiB": {},
                        "ConfigurationLocked": {},
                        "EnvironmentMetrics": {},
                        "Location": {},
                        "Manufacturer": {},
                        "MemoryDeviceType": {},
                        "MemoryMediaType": {},
                        "Metrics": {},
                        "ModuleProductID": {},
                        "NonVolatileSizeMiB": {},
                        "OperatingSpeed": {},
                        "PartNumber": {},
                        "SerialNumber": {},
                        "Status": {},
                        "VolatileSizeMiB": {}
                    }
                }
            ]
        }
    }
}
```

In the last use case, I removed "ReadRequirement" to upgrade it to mandatory. I also changed the comparison to force it to not match anything ("Fred" being a memory type that doesn't exist). In the results, I see the requirement change to Mandatory as expected, but testing it against public-rackmount1, it's a PASS.

image

**Comment by mraineri** [comment]
With the latest changes (and the same profile as above testing against public-rackmount1), I see the first use case marked as FAIL, even though the URI is supported.

image

**Pull request merged**
